name: "Publish Release"
description: "Publish assets and finalize GitHub release"
inputs:
  release_url:
    description: "The full url to the GitHub release page"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -eux
        pip install release-helper
        release-helper publish-release ${{ inputs.release_url }}
