name: "Create Release"
description: "Create a GitHub Release"
inputs:
  token:
    description: "GitHub access token"
    required: true
  version_spec:
    description: "New Version Specifier"
    required: true
  post_version_spec:
    description: "Post Version Specifier"
  changelog:
    description: "Changelog file"
    default: "CHANGELOG.md"
  dry_run:
    description: "If set, do not push permanent changes"
    default: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        pip install release-helper
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export VERSION_SPEC=${{ inputs.version_spec }}
        export CHANGELOG=${{ inputs.changelog }}
        export POST_VERSION_SPEC=${{ inputs.post_version_spec }}
        export DRY_RUN=${{ inputs.dry_run }}
        release-helper prep-env
        release-helper check-changelog
        release-helper build-python
        release-helper check-python dist/*
        release-helper check-manifest
        release-helper check-md-links
        release-helper tag-release
        release-helper publish-release
