name: "Draft Changelog"
description: "Create an automated changelog entry PR"
inputs:
  token:
    description: "GitHub access token"
    required: true
  changelog:
    description: "Changelog file"
    default: "CHANGELOG.md"
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      id: draft-release
      run: |
        set -eux

        # Set up env variables
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_REPOSITORY=${GITHUB_REPOSITORY}
        export RH_VERSION_SPEC=0.0.1a0
        export RH_POST_VERSION_SPEC=0.1.0.dev0
        export RH_CHANGELOG=${{ inputs.changelog }}
        export RH_DRY_RUN=true
        if [ ! -z ${GITHUB_HEAD_REF} ]; then
          echo "Using GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          export RH_BRANCH=${GITHUB_HEAD_REF}
        else
          # e.g refs/head/foo or refs/tag/bar
          echo "Using GITHUB_REF: ${GITHUB_REF}"
          export RH_BRANCH=$(echo ${GITHUB_REF} | cut -d'/' -f 3)
        fi

        # Install Jupyter Releaser from test PYPI server
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple -q jupyter-releaser==0.9.0

        # Draft Changelog
        jupyter-releaser prep-git
        jupyter-releaser bump-version
        jupyter-releaser build-changelog
        jupyter-releaser draft-changelog
        cat ${RH_CHANGELOG}

        # Draft Release
        jupyter-releaser prep-git
        jupyter-releaser bump-version
        jupyter-releaser check-changelog
        #jupyter-releaser check-links
        # Make sure npm comes before python in case it produces
        # files for the python package
        jupyter-releaser build-npm
        jupyter-releaser check-npm
        jupyter-releaser build-python
        jupyter-releaser check-python
        jupyter-releaser check-manifest
        jupyter-releaser tag-release
        jupyter-releaser draft-release

    - shell: bash
      id: publish-release
      run: |
        set -eux

        # Set up env variables
        export release_url=${{ steps.draft-release.outputs.release_url }}
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_REPOSITORY=${GITHUB_REPOSITORY}
        export RH_DRY_RUN=true
        export TWINE_USERNAME=${TWINE_USERNAME:-"__token__"}
        export TWINE_COMMAND=${TWINE_COMMAND:-"twine upload --skip-existing"}
        export TWINE_REPOSITORY_URL=${TWINE_REPOSITORY_URL:-"https://test.pypi.org/legacy/"}
        export RH_NPM_COMMAND=${NPM_COMMAND:-"npm publish --dry-run"}

        # Publish Release
        jupyter-releaser extract-release ${release_url}
        jupyter-releaser forwardport-changelog ${release_url}
        jupyter-releaser publish-release ${release_url}

        # Delete Draft Release
        jupyter-releaser delete-release ${release_url}
