name: "Draft Changelog"
description: "Create an automated changelog entry PR"
inputs:
  token:
    description: "GitHub access token"
    required: true
  version_spec:
    description: "New Version Specifier"
    required: true
  changelog:
    description: "Changelog file"
    default: "CHANGELOG.md"
  dry_run:
    description: "If set, do not make a PR"
    default: false
outputs:
  pr_url:
    description: "The URL of the Changelog Pull Request"
    value: ${{ steps.draft-changelog.outputs.pr_url }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: draft-changelog
      run: |
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export RH_VERSION_SPEC=${{ inputs.version_spec }}
        export RH_CHANGELOG=${{ inputs.changelog }}
        export RH_DRY_RUN=${{ inputs.dry_run }}
        bash .github/scripts/draft-changelog.sh
