name: "Create Changelog"
description: "Create an automated changelog entry"
inputs:
  token:
    description: "GitHub access token"
    required: true
  version_spec:
    description: "New Version Specifier"
    required: true
  changelog:
    description: "Changelog file"
    default: "CHANGELOG.md"
  pull_request_body:
    description: "The pull request body text"
    default: "Automated Changelog"
  dry_run:
    description: "If set, do not make a PR"
    default: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        pip install release-helper
        export GITHUB_ACCESS_TOKEN=${{ inputs.token }}
        export VERSION_SPEC=${{ inputs.version_spec }}
        export CHANGELOG=${{ inputs.changelog }}
        export DRY_RUN=${{ inputs.dry_run }}
        release-helper prep-env
        release-helper prep-changelog
        release-helper publish-changelog --body "${{ inputs.pull_request_body }}"
